import {
  AlertCircle,
  AlertTriangle,
  ArrowUp,
  BarChart3,
  BookOpen,
  Bookmark,
  BookmarkMinus,
  Bot,
  Brain,
  ChartColumn,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  CircleDollarSign,
  Clock,
  Code2,
  Compass,
  Copy,
  Cpu,
  Database,
  Download,
  Eraser,
  FileEdit,
  FileText,
  Folder,
  FolderOpen,
  GitBranch,
  GitMerge,
  Globe,
  HelpCircle,
  History,
  Image,
  LoaderCircle,
  LogOut,
  Map,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minimize2,
  MoreVertical,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pencil,
  Pin,
  Plus,
  RefreshCw,
  ScrollText,
  Search,
  SearchX,
  Send,
  Settings,
  ShieldCheck,
  Star,
  StopCircle,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Map of Material Symbols icon names to lucide-react components.
 * Used for dynamic icon resolution, e.g. `tab.icon` or `link.icon`.
 */
export const iconMap: Record<string, LucideIcon> = {
  account_tree: GitBranch,
  add: Plus,
  admin_panel_settings: ShieldCheck,
  arrow_upward: ArrowUp,
  attach_file: Paperclip,
  bar_chart: BarChart3,
  bolt: Zap,
  build: Wrench,
  chat_bubble: MessageCircle,
  chat_bubble_outline: MessageCircle,
  check: Check,
  check_circle: CheckCircle,
  close: X,
  compress: Minimize2,
  content_copy: Copy,
  data_object: Code2,
  database: Database,
  delete: Trash2,
  delete_forever: Trash,
  delete_outline: Trash2,
  delete_sweep: Eraser,
  description: FileText,
  download: Download,
  drive_file_rename_outline: FileEdit,
  edit: Pencil,
  error: AlertCircle,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  folder: Folder,
  folder_open: FolderOpen,
  forum: MessageSquare,
  help_outline: HelpCircle,
  history: History,
  image: Image,
  insert_chart: ChartColumn,
  keep: Bookmark,
  keep_off: BookmarkMinus,
  keyboard_arrow_down: ChevronDown,
  language: Globe,
  logout: LogOut,
  map: Map,
  memory: Cpu,
  menu: Menu,
  menu_book: BookOpen,
  merge: GitMerge,
  mic: Mic,
  more_vert: MoreVertical,
  person: User,
  progress_activity: LoaderCircle,
  psychology: Brain,
  push_pin: Pin,
  refresh: RefreshCw,
  right_panel_close: PanelRightClose,
  right_panel_open: PanelRightOpen,
  schedule: Clock,
  search: Search,
  search_off: SearchX,
  send: Send,
  settings: Settings,
  smart_toy: Bot,
  star: Star,
  stop_circle: StopCircle,
  text_snippet: ScrollText,
  thumb_down: ThumbsDown,
  thumb_up: ThumbsUp,
  timer: Timer,
  toll: CircleDollarSign,
  travel_explore: Compass,
  trending_up: TrendingUp,
  upload_file: Upload,
  warning: AlertTriangle,
};
